<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>ExternalIPWidget.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ExternalIPWidget.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="ExternalIPWidget.ico" />
  </ItemGroup>

</Project>